// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blinkt_api.proto

package blinktv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetPixelRequest struct {
	Index                uint32     `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Brightness           Brightness `protobuf:"varint,2,opt,name=brightness,proto3,enum=blinkt.v1.Brightness" json:"brightness,omitempty"`
	Color                *Color     `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SetPixelRequest) Reset()         { *m = SetPixelRequest{} }
func (m *SetPixelRequest) String() string { return proto.CompactTextString(m) }
func (*SetPixelRequest) ProtoMessage()    {}
func (*SetPixelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_359c523f0a9c7be0, []int{0}
}

func (m *SetPixelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPixelRequest.Unmarshal(m, b)
}
func (m *SetPixelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPixelRequest.Marshal(b, m, deterministic)
}
func (m *SetPixelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPixelRequest.Merge(m, src)
}
func (m *SetPixelRequest) XXX_Size() int {
	return xxx_messageInfo_SetPixelRequest.Size(m)
}
func (m *SetPixelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPixelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPixelRequest proto.InternalMessageInfo

func (m *SetPixelRequest) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *SetPixelRequest) GetBrightness() Brightness {
	if m != nil {
		return m.Brightness
	}
	return Brightness_BRIGHTNESS_INVALID
}

func (m *SetPixelRequest) GetColor() *Color {
	if m != nil {
		return m.Color
	}
	return nil
}

type SetPixelResponse struct {
	Result               Result   `protobuf:"varint,1,opt,name=result,proto3,enum=blinkt.v1.Result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPixelResponse) Reset()         { *m = SetPixelResponse{} }
func (m *SetPixelResponse) String() string { return proto.CompactTextString(m) }
func (*SetPixelResponse) ProtoMessage()    {}
func (*SetPixelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_359c523f0a9c7be0, []int{1}
}

func (m *SetPixelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPixelResponse.Unmarshal(m, b)
}
func (m *SetPixelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPixelResponse.Marshal(b, m, deterministic)
}
func (m *SetPixelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPixelResponse.Merge(m, src)
}
func (m *SetPixelResponse) XXX_Size() int {
	return xxx_messageInfo_SetPixelResponse.Size(m)
}
func (m *SetPixelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPixelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetPixelResponse proto.InternalMessageInfo

func (m *SetPixelResponse) GetResult() Result {
	if m != nil {
		return m.Result
	}
	return Result_RESULT_INVALID
}

type ClearRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearRequest) Reset()         { *m = ClearRequest{} }
func (m *ClearRequest) String() string { return proto.CompactTextString(m) }
func (*ClearRequest) ProtoMessage()    {}
func (*ClearRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_359c523f0a9c7be0, []int{2}
}

func (m *ClearRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearRequest.Unmarshal(m, b)
}
func (m *ClearRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearRequest.Marshal(b, m, deterministic)
}
func (m *ClearRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearRequest.Merge(m, src)
}
func (m *ClearRequest) XXX_Size() int {
	return xxx_messageInfo_ClearRequest.Size(m)
}
func (m *ClearRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClearRequest proto.InternalMessageInfo

type ClearResponse struct {
	Result               Result   `protobuf:"varint,1,opt,name=result,proto3,enum=blinkt.v1.Result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearResponse) Reset()         { *m = ClearResponse{} }
func (m *ClearResponse) String() string { return proto.CompactTextString(m) }
func (*ClearResponse) ProtoMessage()    {}
func (*ClearResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_359c523f0a9c7be0, []int{3}
}

func (m *ClearResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearResponse.Unmarshal(m, b)
}
func (m *ClearResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearResponse.Marshal(b, m, deterministic)
}
func (m *ClearResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearResponse.Merge(m, src)
}
func (m *ClearResponse) XXX_Size() int {
	return xxx_messageInfo_ClearResponse.Size(m)
}
func (m *ClearResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClearResponse proto.InternalMessageInfo

func (m *ClearResponse) GetResult() Result {
	if m != nil {
		return m.Result
	}
	return Result_RESULT_INVALID
}

type ShowRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowRequest) Reset()         { *m = ShowRequest{} }
func (m *ShowRequest) String() string { return proto.CompactTextString(m) }
func (*ShowRequest) ProtoMessage()    {}
func (*ShowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_359c523f0a9c7be0, []int{4}
}

func (m *ShowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowRequest.Unmarshal(m, b)
}
func (m *ShowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowRequest.Marshal(b, m, deterministic)
}
func (m *ShowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowRequest.Merge(m, src)
}
func (m *ShowRequest) XXX_Size() int {
	return xxx_messageInfo_ShowRequest.Size(m)
}
func (m *ShowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShowRequest proto.InternalMessageInfo

type ShowResponse struct {
	Result               Result   `protobuf:"varint,1,opt,name=result,proto3,enum=blinkt.v1.Result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowResponse) Reset()         { *m = ShowResponse{} }
func (m *ShowResponse) String() string { return proto.CompactTextString(m) }
func (*ShowResponse) ProtoMessage()    {}
func (*ShowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_359c523f0a9c7be0, []int{5}
}

func (m *ShowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowResponse.Unmarshal(m, b)
}
func (m *ShowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowResponse.Marshal(b, m, deterministic)
}
func (m *ShowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowResponse.Merge(m, src)
}
func (m *ShowResponse) XXX_Size() int {
	return xxx_messageInfo_ShowResponse.Size(m)
}
func (m *ShowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShowResponse proto.InternalMessageInfo

func (m *ShowResponse) GetResult() Result {
	if m != nil {
		return m.Result
	}
	return Result_RESULT_INVALID
}

func init() {
	proto.RegisterType((*SetPixelRequest)(nil), "blinkt.v1.SetPixelRequest")
	proto.RegisterType((*SetPixelResponse)(nil), "blinkt.v1.SetPixelResponse")
	proto.RegisterType((*ClearRequest)(nil), "blinkt.v1.ClearRequest")
	proto.RegisterType((*ClearResponse)(nil), "blinkt.v1.ClearResponse")
	proto.RegisterType((*ShowRequest)(nil), "blinkt.v1.ShowRequest")
	proto.RegisterType((*ShowResponse)(nil), "blinkt.v1.ShowResponse")
}

func init() { proto.RegisterFile("blinkt_api.proto", fileDescriptor_359c523f0a9c7be0) }

var fileDescriptor_359c523f0a9c7be0 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4f, 0xc2, 0x30,
	0x14, 0xc7, 0x53, 0x10, 0x02, 0x0f, 0x36, 0xb1, 0x51, 0x59, 0xe6, 0x85, 0xec, 0x60, 0xf0, 0xb2,
	0x84, 0x19, 0x63, 0x24, 0xe1, 0xe0, 0x38, 0x79, 0x5b, 0x4a, 0x62, 0x88, 0x17, 0x03, 0xd8, 0x48,
	0xe3, 0x5c, 0xe7, 0x5a, 0x10, 0xbf, 0x80, 0x1f, 0xc4, 0xa3, 0xdf, 0xc3, 0xef, 0x65, 0x58, 0x0b,
	0x6b, 0xc4, 0x0b, 0xc7, 0xf7, 0x7e, 0xfd, 0xbf, 0xf6, 0xd7, 0x3c, 0x68, 0x4d, 0x63, 0x96, 0xbc,
	0xc8, 0xc7, 0x49, 0xca, 0xfc, 0x34, 0xe3, 0x92, 0xe3, 0xba, 0xea, 0xf8, 0xcb, 0x9e, 0x8b, 0x35,
	0x94, 0x1f, 0x29, 0x15, 0x0a, 0x7b, 0x9f, 0x08, 0x0e, 0x47, 0x54, 0x46, 0x6c, 0x45, 0x63, 0x42,
	0xdf, 0x16, 0x54, 0x48, 0x7c, 0x0c, 0x15, 0x96, 0x3c, 0xd1, 0x95, 0x83, 0x3a, 0xa8, 0x6b, 0x11,
	0x55, 0xe0, 0x2b, 0x80, 0x69, 0xc6, 0x9e, 0xe7, 0x32, 0xa1, 0x42, 0x38, 0xa5, 0x0e, 0xea, 0xda,
	0xc1, 0x89, 0xbf, 0x9d, 0xee, 0x87, 0x5b, 0x48, 0x8c, 0x83, 0xf8, 0x1c, 0x2a, 0x33, 0x1e, 0xf3,
	0xcc, 0x29, 0x77, 0x50, 0xb7, 0x11, 0xb4, 0x8c, 0xc4, 0x70, 0xdd, 0x27, 0x0a, 0x7b, 0x03, 0x68,
	0x15, 0xef, 0x10, 0x29, 0x4f, 0x04, 0xc5, 0x17, 0x50, 0xcd, 0xa8, 0x58, 0xc4, 0x32, 0x7f, 0x89,
	0x1d, 0x1c, 0x19, 0x61, 0x92, 0x03, 0xa2, 0x0f, 0x78, 0x36, 0x34, 0x87, 0x31, 0x9d, 0x64, 0xda,
	0xc1, 0xeb, 0x83, 0xa5, 0xeb, 0xfd, 0x67, 0x59, 0xd0, 0x18, 0xcd, 0xf9, 0xfb, 0x66, 0xd4, 0x0d,
	0x34, 0x55, 0xb9, 0xf7, 0xa4, 0xe0, 0x07, 0x41, 0x3d, 0xcc, 0xe1, 0x6d, 0x74, 0x87, 0x87, 0x50,
	0xdb, 0x28, 0x62, 0xd7, 0x08, 0xfd, 0xf9, 0x7f, 0xf7, 0xec, 0x5f, 0xa6, 0x6f, 0xef, 0x43, 0x25,
	0x17, 0xc3, 0x6d, 0xf3, 0x27, 0x0d, 0x75, 0xd7, 0xd9, 0x05, 0x3a, 0x7b, 0x0d, 0x07, 0x6b, 0x13,
	0x7c, 0x6a, 0x5e, 0x50, 0x98, 0xba, 0xed, 0x9d, 0xbe, 0x0a, 0x86, 0x03, 0xb0, 0x66, 0xfc, 0xb5,
	0xa0, 0xa1, 0xad, 0xad, 0x52, 0x16, 0xad, 0xd7, 0x28, 0x42, 0x0f, 0x35, 0x05, 0x97, 0xbd, 0xaf,
	0x52, 0x39, 0x1c, 0x8f, 0xbf, 0x4b, 0x5a, 0xdc, 0xbf, 0xef, 0x4d, 0xab, 0xf9, 0xae, 0x5d, 0xfe,
	0x06, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x8b, 0x1b, 0xf6, 0x9e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlinktAPIClient is the client API for BlinktAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlinktAPIClient interface {
	// Set color and brightness of an LED.
	// The change is not displayed until Show is called.
	SetPixel(ctx context.Context, in *SetPixelRequest, opts ...grpc.CallOption) (*SetPixelResponse, error)
	// Turn all LEDs off.
	// The change is not displayed until Show is called.
	Clear(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ClearResponse, error)
	// Update all the LEDs.
	Show(ctx context.Context, in *ShowRequest, opts ...grpc.CallOption) (*ShowResponse, error)
}

type blinktAPIClient struct {
	cc *grpc.ClientConn
}

func NewBlinktAPIClient(cc *grpc.ClientConn) BlinktAPIClient {
	return &blinktAPIClient{cc}
}

func (c *blinktAPIClient) SetPixel(ctx context.Context, in *SetPixelRequest, opts ...grpc.CallOption) (*SetPixelResponse, error) {
	out := new(SetPixelResponse)
	err := c.cc.Invoke(ctx, "/blinkt.v1.BlinktAPI/SetPixel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blinktAPIClient) Clear(ctx context.Context, in *ClearRequest, opts ...grpc.CallOption) (*ClearResponse, error) {
	out := new(ClearResponse)
	err := c.cc.Invoke(ctx, "/blinkt.v1.BlinktAPI/Clear", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blinktAPIClient) Show(ctx context.Context, in *ShowRequest, opts ...grpc.CallOption) (*ShowResponse, error) {
	out := new(ShowResponse)
	err := c.cc.Invoke(ctx, "/blinkt.v1.BlinktAPI/Show", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlinktAPIServer is the server API for BlinktAPI service.
type BlinktAPIServer interface {
	// Set color and brightness of an LED.
	// The change is not displayed until Show is called.
	SetPixel(context.Context, *SetPixelRequest) (*SetPixelResponse, error)
	// Turn all LEDs off.
	// The change is not displayed until Show is called.
	Clear(context.Context, *ClearRequest) (*ClearResponse, error)
	// Update all the LEDs.
	Show(context.Context, *ShowRequest) (*ShowResponse, error)
}

func RegisterBlinktAPIServer(s *grpc.Server, srv BlinktAPIServer) {
	s.RegisterService(&_BlinktAPI_serviceDesc, srv)
}

func _BlinktAPI_SetPixel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPixelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlinktAPIServer).SetPixel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blinkt.v1.BlinktAPI/SetPixel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlinktAPIServer).SetPixel(ctx, req.(*SetPixelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlinktAPI_Clear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlinktAPIServer).Clear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blinkt.v1.BlinktAPI/Clear",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlinktAPIServer).Clear(ctx, req.(*ClearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlinktAPI_Show_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlinktAPIServer).Show(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blinkt.v1.BlinktAPI/Show",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlinktAPIServer).Show(ctx, req.(*ShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlinktAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blinkt.v1.BlinktAPI",
	HandlerType: (*BlinktAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetPixel",
			Handler:    _BlinktAPI_SetPixel_Handler,
		},
		{
			MethodName: "Clear",
			Handler:    _BlinktAPI_Clear_Handler,
		},
		{
			MethodName: "Show",
			Handler:    _BlinktAPI_Show_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blinkt_api.proto",
}
